/**
 * Built-in VS Code themes with full color definitions
 * 
 * These themes include both UI colors and are compatible with Shiki for syntax highlighting.
 * Each theme has been curated to work well with the app's design system.
 */

import type { VSCodeFullTheme } from "../atoms"
import { CURSOR_DARK, CURSOR_LIGHT, CURSOR_MIDNIGHT } from "./cursor-themes"

/**
 * 21st Dark - Default dark theme matching the app's original design
 * Uses the brand blue (#0034FF) as primary/accent color
 */
const TWENTYFIRST_DARK: VSCodeFullTheme = {
  id: "21st-dark",
  name: "21st Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#0a0a0a", // 240 10% 3.9%
    "editor.foreground": "#f4f4f5", // 240 4.8% 95.9%
    "foreground": "#f4f4f5",
    "sideBar.background": "#121212", // original tl-background (0 0% 7%)
    "sideBar.foreground": "#f4f4f5",
    "sideBar.border": "#27272a", // 240 3.7% 15.9%
    "activityBar.background": "#0a0a0a",
    "activityBar.foreground": "#f4f4f5",
    "panel.background": "#121212", // match sidebar
    "panel.border": "#27272a",
    "tab.activeBackground": "#0a0a0a",
    "tab.inactiveBackground": "#18181b", // 240 5.9% 10%
    "tab.inactiveForeground": "#a1a1aa", // 240 4.4% 58%
    "editorGroupHeader.tabsBackground": "#18181b",
    "dropdown.background": "#171717", // popover
    "dropdown.foreground": "#fafafa",
    "input.background": "#121212", // same as sidebar/tl-background
    "input.border": "#27272a",
    "input.foreground": "#f4f4f5",
    "focusBorder": "#0034ff", // primary blue
    "textLink.foreground": "#0034ff",
    "textLink.activeForeground": "#3366ff",
    "list.activeSelectionBackground": "#27272a",
    "list.hoverBackground": "#18181b",
    "editor.selectionBackground": "#0034ff44",
    "editorLineNumber.foreground": "#52525b",
    "descriptionForeground": "#a1a1aa",
    "errorForeground": "#ef4444",
    "button.background": "#0034ff", // primary
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#27272a",
    "button.secondaryForeground": "#fafafa",
    // Terminal colors
    "terminal.background": "#0a0a0a",
    "terminal.foreground": "#f4f4f5",
    "terminal.ansiBlack": "#18181b",
    "terminal.ansiRed": "#ef4444",
    "terminal.ansiGreen": "#22c55e",
    "terminal.ansiYellow": "#eab308",
    "terminal.ansiBlue": "#3b82f6",
    "terminal.ansiMagenta": "#a855f7",
    "terminal.ansiCyan": "#06b6d4",
    "terminal.ansiWhite": "#f4f4f5",
    "terminal.ansiBrightBlack": "#71717a",
    "terminal.ansiBrightRed": "#f87171",
    "terminal.ansiBrightGreen": "#4ade80",
    "terminal.ansiBrightYellow": "#facc15",
    "terminal.ansiBrightBlue": "#60a5fa",
    "terminal.ansiBrightMagenta": "#c084fc",
    "terminal.ansiBrightCyan": "#22d3ee",
    "terminal.ansiBrightWhite": "#fafafa",
  },
}

/**
 * 21st Light - Default light theme matching the app's original design
 * Uses the brand blue (#0034FF) as primary/accent color
 */
const TWENTYFIRST_LIGHT: VSCodeFullTheme = {
  id: "21st-light",
  name: "21st Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#0a0a0a", // 240 10% 3.9%
    "foreground": "#0a0a0a",
    "sideBar.background": "#FAFAFA", // original tl-background (0 0% 98%)
    "sideBar.foreground": "#0a0a0a",
    "sideBar.border": "#e4e4e7", // 240 5.9% 90%
    "activityBar.background": "#ffffff",
    "activityBar.foreground": "#0a0a0a",
    "panel.background": "#FAFAFA", // match sidebar
    "panel.border": "#e4e4e7",
    "tab.activeBackground": "#ffffff",
    "tab.inactiveBackground": "#f4f4f5", // 240 4.8% 95.9%
    "tab.inactiveForeground": "#71717a", // 240 3.8% 46.1%
    "editorGroupHeader.tabsBackground": "#f4f4f5",
    "dropdown.background": "#ffffff",
    "dropdown.foreground": "#0a0a0a",
    "input.background": "#FAFAFA", // same as sidebar/tl-background
    "input.border": "#e4e4e7",
    "input.foreground": "#0a0a0a",
    "focusBorder": "#0034ff", // primary blue
    "textLink.foreground": "#0034ff",
    "textLink.activeForeground": "#0028cc",
    "list.activeSelectionBackground": "#f4f4f5",
    "list.hoverBackground": "#f4f4f5",
    "editor.selectionBackground": "#0034ff33",
    "editorLineNumber.foreground": "#a1a1aa",
    "descriptionForeground": "#71717a",
    "errorForeground": "#dc2626",
    "button.background": "#0034ff", // primary
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#f4f4f5",
    "button.secondaryForeground": "#18181b",
    // Terminal colors
    "terminal.background": "#fafafa",
    "terminal.foreground": "#0a0a0a",
    "terminal.ansiBlack": "#18181b",
    "terminal.ansiRed": "#dc2626",
    "terminal.ansiGreen": "#16a34a",
    "terminal.ansiYellow": "#ca8a04",
    "terminal.ansiBlue": "#2563eb",
    "terminal.ansiMagenta": "#9333ea",
    "terminal.ansiCyan": "#0891b2",
    "terminal.ansiWhite": "#f4f4f5",
    "terminal.ansiBrightBlack": "#52525b",
    "terminal.ansiBrightRed": "#ef4444",
    "terminal.ansiBrightGreen": "#22c55e",
    "terminal.ansiBrightYellow": "#eab308",
    "terminal.ansiBrightBlue": "#3b82f6",
    "terminal.ansiBrightMagenta": "#a855f7",
    "terminal.ansiBrightCyan": "#06b6d4",
    "terminal.ansiBrightWhite": "#fafafa",
  },
}


/**
 * Vitesse Dark theme colors
 */
const VITESSE_DARK: VSCodeFullTheme = {
  id: "vitesse-dark",
  name: "Vitesse Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#121212",
    "editor.foreground": "#dbd7ca",
    "foreground": "#dbd7ca",
    "sideBar.background": "#121212",
    "sideBar.foreground": "#dbd7ca",
    "sideBar.border": "#1e1e1e",
    "activityBar.background": "#121212",
    "activityBar.foreground": "#dbd7ca",
    "panel.background": "#121212",
    "panel.border": "#1e1e1e",
    "tab.activeBackground": "#1e1e1e",
    "tab.inactiveBackground": "#121212",
    "tab.inactiveForeground": "#75715e",
    "editorGroupHeader.tabsBackground": "#121212",
    "dropdown.background": "#1e1e1e",
    "dropdown.foreground": "#dbd7ca",
    "input.background": "#1e1e1e",
    "input.border": "#2e2e2e",
    "input.foreground": "#dbd7ca",
    "focusBorder": "#4d9375",
    "textLink.foreground": "#4d9375",
    "textLink.activeForeground": "#5eaab5",
    "list.activeSelectionBackground": "#4d937530",
    "list.hoverBackground": "#1e1e1e",
    "editor.selectionBackground": "#4d937540",
    "editorLineNumber.foreground": "#444444",
    "descriptionForeground": "#75715e",
    "errorForeground": "#cb7676",
    "button.background": "#4d9375",
    "button.foreground": "#121212",
    "button.secondaryBackground": "#2e2e2e",
    "button.secondaryForeground": "#dbd7ca",
    // Terminal colors
    "terminal.background": "#121212",
    "terminal.foreground": "#dbd7ca",
    "terminal.ansiBlack": "#393a34",
    "terminal.ansiRed": "#cb7676",
    "terminal.ansiGreen": "#4d9375",
    "terminal.ansiYellow": "#e6cc77",
    "terminal.ansiBlue": "#6394bf",
    "terminal.ansiMagenta": "#d9739f",
    "terminal.ansiCyan": "#5eaab5",
    "terminal.ansiWhite": "#dbd7ca",
    "terminal.ansiBrightBlack": "#666666",
    "terminal.ansiBrightRed": "#cb7676",
    "terminal.ansiBrightGreen": "#4d9375",
    "terminal.ansiBrightYellow": "#e6cc77",
    "terminal.ansiBrightBlue": "#6394bf",
    "terminal.ansiBrightMagenta": "#d9739f",
    "terminal.ansiBrightCyan": "#5eaab5",
    "terminal.ansiBrightWhite": "#eeeeee",
  },
}

/**
 * Vitesse Light theme colors
 */
const VITESSE_LIGHT: VSCodeFullTheme = {
  id: "vitesse-light",
  name: "Vitesse Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#393a34",
    "foreground": "#393a34",
    "sideBar.background": "#fafafa",
    "sideBar.foreground": "#393a34",
    "sideBar.border": "#eeeeee",
    "activityBar.background": "#fafafa",
    "activityBar.foreground": "#393a34",
    "panel.background": "#fafafa",
    "panel.border": "#eeeeee",
    "tab.activeBackground": "#ffffff",
    "tab.inactiveBackground": "#fafafa",
    "tab.inactiveForeground": "#999999",
    "editorGroupHeader.tabsBackground": "#fafafa",
    "dropdown.background": "#ffffff",
    "dropdown.foreground": "#393a34",
    "input.background": "#f5f5f5", // slightly gray for visibility
    "input.border": "#eeeeee",
    "input.foreground": "#393a34",
    "focusBorder": "#1e754f",
    "textLink.foreground": "#1e754f",
    "textLink.activeForeground": "#2993a3",
    "list.activeSelectionBackground": "#eeeeee66",
    "list.hoverBackground": "#f5f5f5",
    "editor.selectionBackground": "#22222215",
    "editorLineNumber.foreground": "#aaaaaa",
    "descriptionForeground": "#999999",
    "errorForeground": "#ab5959",
    "button.background": "#1e754f",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#eeeeee",
    "button.secondaryForeground": "#393a34",
    // Terminal colors
    "terminal.background": "#fafafa", // match sidebar
    "terminal.foreground": "#393a34",
    "terminal.ansiBlack": "#393a34",
    "terminal.ansiRed": "#ab5959",
    "terminal.ansiGreen": "#1e754f",
    "terminal.ansiYellow": "#a65e2b",
    "terminal.ansiBlue": "#296aa3",
    "terminal.ansiMagenta": "#a13865",
    "terminal.ansiCyan": "#2993a3",
    "terminal.ansiWhite": "#b0b0b0",
    "terminal.ansiBrightBlack": "#777777",
    "terminal.ansiBrightRed": "#ab5959",
    "terminal.ansiBrightGreen": "#1e754f",
    "terminal.ansiBrightYellow": "#a65e2b",
    "terminal.ansiBrightBlue": "#296aa3",
    "terminal.ansiBrightMagenta": "#a13865",
    "terminal.ansiBrightCyan": "#2993a3",
    "terminal.ansiBrightWhite": "#393a34",
  },
}


/**
 * Min Dark theme colors (minimal dark theme)
 */
const MIN_DARK: VSCodeFullTheme = {
  id: "min-dark",
  name: "Min Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#1f1f1f",
    "editor.foreground": "#d4d4d4",
    "foreground": "#d4d4d4",
    "sideBar.background": "#181818",
    "sideBar.foreground": "#d4d4d4",
    "sideBar.border": "#252525",
    "activityBar.background": "#181818",
    "activityBar.foreground": "#d4d4d4",
    "panel.background": "#1f1f1f",
    "panel.border": "#252525",
    "tab.activeBackground": "#1f1f1f",
    "tab.inactiveBackground": "#181818",
    "tab.inactiveForeground": "#6e6e6e",
    "editorGroupHeader.tabsBackground": "#181818",
    "dropdown.background": "#252525",
    "dropdown.foreground": "#d4d4d4",
    "input.background": "#181818",
    "input.border": "#3c3c3c",
    "input.foreground": "#d4d4d4",
    "focusBorder": "#6ca1ef",
    "textLink.foreground": "#6ca1ef",
    "textLink.activeForeground": "#89b4fa",
    "list.activeSelectionBackground": "#2a2a2a",
    "list.hoverBackground": "#252525",
    "editor.selectionBackground": "#264f78",
    "editorLineNumber.foreground": "#5a5a5a",
    "descriptionForeground": "#6e6e6e",
    "errorForeground": "#f48771",
    "button.background": "#6ca1ef",
    "button.foreground": "#1f1f1f",
    "button.secondaryBackground": "#3c3c3c",
    "button.secondaryForeground": "#d4d4d4",
    // Terminal colors
    "terminal.background": "#1f1f1f",
    "terminal.foreground": "#d4d4d4",
    "terminal.ansiBlack": "#1f1f1f",
    "terminal.ansiRed": "#f48771",
    "terminal.ansiGreen": "#89d185",
    "terminal.ansiYellow": "#e5c07b",
    "terminal.ansiBlue": "#6ca1ef",
    "terminal.ansiMagenta": "#d38aea",
    "terminal.ansiCyan": "#4ec9b0",
    "terminal.ansiWhite": "#d4d4d4",
    "terminal.ansiBrightBlack": "#6e6e6e",
    "terminal.ansiBrightRed": "#f48771",
    "terminal.ansiBrightGreen": "#89d185",
    "terminal.ansiBrightYellow": "#e5c07b",
    "terminal.ansiBrightBlue": "#6ca1ef",
    "terminal.ansiBrightMagenta": "#d38aea",
    "terminal.ansiBrightCyan": "#4ec9b0",
    "terminal.ansiBrightWhite": "#e5e5e5",
  },
}

/**
 * Vesper Dark theme colors
 * By Rauno Freiberg - https://github.com/raunofreiberg/vesper
 */
const VESPER_DARK: VSCodeFullTheme = {
  id: "vesper-dark",
  name: "Vesper",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#101010",
    "editorPane.background": "#101010",
    "editor.foreground": "#FFFFFF",
    "foreground": "#FFFFFF",
    "sideBar.background": "#101010",
    "sideBar.foreground": "#A0A0A0",
    "sideBar.border": "#232323",
    "activityBar.background": "#101010",
    "activityBar.foreground": "#A0A0A0",
    "activityBarBadge.background": "#FFC799",
    "activityBarBadge.foreground": "#000000",
    "panel.background": "#101010",
    "panel.border": "#232323",
    "tab.activeBackground": "#161616",
    "tab.inactiveBackground": "#101010",
    "tab.inactiveForeground": "#505050",
    "editorGroupHeader.tabsBackground": "#101010",
    "dropdown.background": "#161616",
    "dropdown.foreground": "#FFFFFF",
    "input.background": "#1B1B1B",
    "input.border": "#282828",
    "input.foreground": "#FFFFFF",
    "focusBorder": "#FFC799",
    "textLink.foreground": "#FFC799",
    "textLink.activeForeground": "#FFCFA8",
    "list.activeSelectionBackground": "#232323",
    "list.hoverBackground": "#282828",
    "editor.selectionBackground": "#FFFFFF25",
    "editorLineNumber.foreground": "#505050",
    "descriptionForeground": "#A0A0A0",
    "errorForeground": "#FF8080",
    "button.background": "#FFC799",
    "button.foreground": "#000000",
    "button.secondaryBackground": "#232323",
    "button.secondaryForeground": "#FFFFFF",
    // Terminal colors
    "terminal.background": "#101010",
    "terminal.foreground": "#FFFFFF",
    "terminal.ansiBlack": "#1C1C1C",
    "terminal.ansiRed": "#FF8080",
    "terminal.ansiGreen": "#99FFE4",
    "terminal.ansiYellow": "#FFC799",
    "terminal.ansiBlue": "#A0A0A0",
    "terminal.ansiMagenta": "#FFC799",
    "terminal.ansiCyan": "#99FFE4",
    "terminal.ansiWhite": "#FFFFFF",
    "terminal.ansiBrightBlack": "#505050",
    "terminal.ansiBrightRed": "#FF8080",
    "terminal.ansiBrightGreen": "#99FFE4",
    "terminal.ansiBrightYellow": "#FFC799",
    "terminal.ansiBrightBlue": "#A0A0A0",
    "terminal.ansiBrightMagenta": "#FFC799",
    "terminal.ansiBrightCyan": "#99FFE4",
    "terminal.ansiBrightWhite": "#FFFFFF",
  },
}

/**
 * Min Light theme colors (minimal light theme)
 */
const MIN_LIGHT: VSCodeFullTheme = {
  id: "min-light",
  name: "Min Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#1f1f1f",
    "foreground": "#1f1f1f",
    "sideBar.background": "#f3f3f3",
    "sideBar.foreground": "#1f1f1f",
    "sideBar.border": "#e0e0e0",
    "activityBar.background": "#f3f3f3",
    "activityBar.foreground": "#1f1f1f",
    "panel.background": "#f3f3f3", // match sidebar
    "panel.border": "#e0e0e0",
    "tab.activeBackground": "#ffffff",
    "tab.inactiveBackground": "#f3f3f3",
    "tab.inactiveForeground": "#717171",
    "editorGroupHeader.tabsBackground": "#f3f3f3",
    "dropdown.background": "#ffffff",
    "dropdown.foreground": "#1f1f1f",
    "input.background": "#f3f3f3", // match sidebar for visibility
    "input.border": "#cecece",
    "input.foreground": "#1f1f1f",
    "focusBorder": "#0451a5",
    "textLink.foreground": "#0451a5",
    "textLink.activeForeground": "#0066cc",
    "list.activeSelectionBackground": "#e8e8e8",
    "list.hoverBackground": "#f3f3f3",
    "editor.selectionBackground": "#add6ff",
    "editorLineNumber.foreground": "#6e7681",
    "descriptionForeground": "#717171",
    "errorForeground": "#d32f2f",
    "button.background": "#0451a5",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#e0e0e0",
    "button.secondaryForeground": "#1f1f1f",
    // Terminal colors
    "terminal.background": "#f3f3f3", // match sidebar
    "terminal.foreground": "#1f1f1f",
    "terminal.ansiBlack": "#1f1f1f",
    "terminal.ansiRed": "#cd3131",
    "terminal.ansiGreen": "#14ce14",
    "terminal.ansiYellow": "#949800",
    "terminal.ansiBlue": "#0451a5",
    "terminal.ansiMagenta": "#bc05bc",
    "terminal.ansiCyan": "#0598bc",
    "terminal.ansiWhite": "#a5a5a5",
    "terminal.ansiBrightBlack": "#717171",
    "terminal.ansiBrightRed": "#cd3131",
    "terminal.ansiBrightGreen": "#14ce14",
    "terminal.ansiBrightYellow": "#b5ba00",
    "terminal.ansiBrightBlue": "#0451a5",
    "terminal.ansiBrightMagenta": "#bc05bc",
    "terminal.ansiBrightCyan": "#0598bc",
    "terminal.ansiBrightWhite": "#1f1f1f",
  },
}

/**
 * Claude Light theme colors
 * Warm, beige tones with orange accent (Claude's signature color)
 */
const CLAUDE_LIGHT: VSCodeFullTheme = {
  id: "claude-light",
  name: "Claude Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#FAF9F5",
    "editorPane.background": "#FAF9F5",
    "editor.foreground": "#4a4538",
    "foreground": "#4a4538",
    "sideBar.background": "#FAF9F5",
    "sideBar.foreground": "#4a4538",
    "sideBar.border": "#e5e3de",
    "activityBar.background": "#FAF9F5",
    "activityBar.foreground": "#4a4538",
    "panel.background": "#FAF9F5",
    "panel.border": "#e5e3de",
    "tab.activeBackground": "#FAF9F5",
    "tab.inactiveBackground": "#f5f4f1",
    "tab.inactiveForeground": "#8b8578",
    "editorGroupHeader.tabsBackground": "#f5f4f1",
    "dropdown.background": "#ffffff",
    "dropdown.foreground": "#4a4538",
    "input.background": "#ffffff",
    "input.border": "#d5d3ce",
    "input.foreground": "#4a4538",
    "focusBorder": "#D97857",
    "textLink.foreground": "#D97857",
    "textLink.activeForeground": "#C4684A",
    "list.activeSelectionBackground": "#e8e5dd",
    "list.hoverBackground": "#f0ede7",
    "editor.selectionBackground": "#D9785733",
    "editorLineNumber.foreground": "#a5a193",
    "descriptionForeground": "#8b8578",
    "errorForeground": "#dc2626",
    "button.background": "#D97857",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#e8e5dd",
    "button.secondaryForeground": "#4a4538",
    // Terminal colors
    "terminal.background": "#FAF9F5",
    "terminal.foreground": "#4a4538",
    "terminal.ansiBlack": "#4a4538",
    "terminal.ansiRed": "#dc2626",
    "terminal.ansiGreen": "#16a34a",
    "terminal.ansiYellow": "#D97857",
    "terminal.ansiBlue": "#2563eb",
    "terminal.ansiMagenta": "#9333ea",
    "terminal.ansiCyan": "#0891b2",
    "terminal.ansiWhite": "#e5e3de",
    "terminal.ansiBrightBlack": "#8b8578",
    "terminal.ansiBrightRed": "#ef4444",
    "terminal.ansiBrightGreen": "#22c55e",
    "terminal.ansiBrightYellow": "#f59e0b",
    "terminal.ansiBrightBlue": "#3b82f6",
    "terminal.ansiBrightMagenta": "#a855f7",
    "terminal.ansiBrightCyan": "#06b6d4",
    "terminal.ansiBrightWhite": "#FAF9F5",
  },
}

/**
 * Claude Dark theme colors
 * Warm dark tones with orange accent (Claude's signature color)
 */
const CLAUDE_DARK: VSCodeFullTheme = {
  id: "claude-dark",
  name: "Claude Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#262624",
    "editorPane.background": "#262624",
    "editor.foreground": "#c9c5bc",
    "foreground": "#c9c5bc",
    "sideBar.background": "#262624",
    "sideBar.foreground": "#c9c5bc",
    "sideBar.border": "#3a3937",
    "activityBar.background": "#262624",
    "activityBar.foreground": "#c9c5bc",
    "panel.background": "#262624",
    "panel.border": "#3d3a36",
    "tab.activeBackground": "#262624",
    "tab.inactiveBackground": "#262624",
    "tab.inactiveForeground": "#8a857c",
    "editorGroupHeader.tabsBackground": "#232120",
    "dropdown.background": "#383633",
    "dropdown.foreground": "#c9c5bc",
    "input.background": "#232120",
    "input.border": "#4a4742",
    "input.foreground": "#c9c5bc",
    "focusBorder": "#D97857",
    "textLink.foreground": "#D97857",
    "textLink.activeForeground": "#E8917A",
    "list.activeSelectionBackground": "#3d3a36",
    "list.hoverBackground": "#353230",
    "editor.selectionBackground": "#D9785744",
    "editorLineNumber.foreground": "#6b6660",
    "descriptionForeground": "#8a857c",
    "errorForeground": "#ef4444",
    "button.background": "#D97857",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#3d3a36",
    "button.secondaryForeground": "#c9c5bc",
    // Terminal colors
    "terminal.background": "#262624",
    "terminal.foreground": "#c9c5bc",
    "terminal.ansiBlack": "#232120",
    "terminal.ansiRed": "#ef4444",
    "terminal.ansiGreen": "#22c55e",
    "terminal.ansiYellow": "#D97857",
    "terminal.ansiBlue": "#3b82f6",
    "terminal.ansiMagenta": "#a855f7",
    "terminal.ansiCyan": "#06b6d4",
    "terminal.ansiWhite": "#c9c5bc",
    "terminal.ansiBrightBlack": "#6b6660",
    "terminal.ansiBrightRed": "#f87171",
    "terminal.ansiBrightGreen": "#4ade80",
    "terminal.ansiBrightYellow": "#fbbf24",
    "terminal.ansiBrightBlue": "#60a5fa",
    "terminal.ansiBrightMagenta": "#c084fc",
    "terminal.ansiBrightCyan": "#22d3ee",
    "terminal.ansiBrightWhite": "#e5e3de",
  },
}

/**
 * Dracula theme colors
 * Classic dark theme with purple accent
 */
const DRACULA: VSCodeFullTheme = {
  id: "dracula",
  name: "Dracula",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "foreground": "#f8f8f2",
    "sideBar.background": "#21222c",
    "sideBar.foreground": "#f8f8f2",
    "sideBar.border": "#44475a",
    "activityBar.background": "#21222c",
    "activityBar.foreground": "#f8f8f2",
    "panel.background": "#282a36",
    "panel.border": "#44475a",
    "tab.activeBackground": "#282a36",
    "tab.inactiveBackground": "#21222c",
    "tab.inactiveForeground": "#6272a4",
    "editorGroupHeader.tabsBackground": "#21222c",
    "dropdown.background": "#21222c",
    "dropdown.foreground": "#f8f8f2",
    "input.background": "#21222c",
    "input.border": "#44475a",
    "input.foreground": "#f8f8f2",
    "focusBorder": "#bd93f9",
    "textLink.foreground": "#bd93f9",
    "textLink.activeForeground": "#ff79c6",
    "list.activeSelectionBackground": "#44475a",
    "list.hoverBackground": "#44475a80",
    "editor.selectionBackground": "#44475a",
    "editorLineNumber.foreground": "#6272a4",
    "descriptionForeground": "#6272a4",
    "errorForeground": "#ff5555",
    "button.background": "#bd93f9",
    "button.foreground": "#282a36",
    "button.secondaryBackground": "#44475a",
    "button.secondaryForeground": "#f8f8f2",
    "terminal.background": "#282a36",
    "terminal.foreground": "#f8f8f2",
    "terminal.ansiBlack": "#21222c",
    "terminal.ansiRed": "#ff5555",
    "terminal.ansiGreen": "#50fa7b",
    "terminal.ansiYellow": "#f1fa8c",
    "terminal.ansiBlue": "#bd93f9",
    "terminal.ansiMagenta": "#ff79c6",
    "terminal.ansiCyan": "#8be9fd",
    "terminal.ansiWhite": "#f8f8f2",
    "terminal.ansiBrightBlack": "#6272a4",
    "terminal.ansiBrightRed": "#ff6e6e",
    "terminal.ansiBrightGreen": "#69ff94",
    "terminal.ansiBrightYellow": "#ffffa5",
    "terminal.ansiBrightBlue": "#d6acff",
    "terminal.ansiBrightMagenta": "#ff92df",
    "terminal.ansiBrightCyan": "#a4ffff",
    "terminal.ansiBrightWhite": "#ffffff",
  },
}

/**
 * Nord theme colors
 * Arctic, north-bluish clean theme
 */
const NORD: VSCodeFullTheme = {
  id: "nord",
  name: "Nord",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#2e3440",
    "editor.foreground": "#d8dee9",
    "foreground": "#d8dee9",
    "sideBar.background": "#2e3440",
    "sideBar.foreground": "#d8dee9",
    "sideBar.border": "#3b4252",
    "activityBar.background": "#2e3440",
    "activityBar.foreground": "#d8dee9",
    "panel.background": "#2e3440",
    "panel.border": "#3b4252",
    "tab.activeBackground": "#3b4252",
    "tab.inactiveBackground": "#2e3440",
    "tab.inactiveForeground": "#4c566a",
    "editorGroupHeader.tabsBackground": "#2e3440",
    "dropdown.background": "#3b4252",
    "dropdown.foreground": "#d8dee9",
    "input.background": "#3b4252",
    "input.border": "#4c566a",
    "input.foreground": "#d8dee9",
    "focusBorder": "#88c0d0",
    "textLink.foreground": "#88c0d0",
    "textLink.activeForeground": "#8fbcbb",
    "list.activeSelectionBackground": "#3b4252",
    "list.hoverBackground": "#434c5e",
    "editor.selectionBackground": "#434c5e",
    "editorLineNumber.foreground": "#4c566a",
    "descriptionForeground": "#4c566a",
    "errorForeground": "#bf616a",
    "button.background": "#88c0d0",
    "button.foreground": "#2e3440",
    "button.secondaryBackground": "#4c566a",
    "button.secondaryForeground": "#d8dee9",
    "terminal.background": "#2e3440",
    "terminal.foreground": "#d8dee9",
    "terminal.ansiBlack": "#3b4252",
    "terminal.ansiRed": "#bf616a",
    "terminal.ansiGreen": "#a3be8c",
    "terminal.ansiYellow": "#ebcb8b",
    "terminal.ansiBlue": "#81a1c1",
    "terminal.ansiMagenta": "#b48ead",
    "terminal.ansiCyan": "#88c0d0",
    "terminal.ansiWhite": "#e5e9f0",
    "terminal.ansiBrightBlack": "#4c566a",
    "terminal.ansiBrightRed": "#bf616a",
    "terminal.ansiBrightGreen": "#a3be8c",
    "terminal.ansiBrightYellow": "#ebcb8b",
    "terminal.ansiBrightBlue": "#81a1c1",
    "terminal.ansiBrightMagenta": "#b48ead",
    "terminal.ansiBrightCyan": "#8fbcbb",
    "terminal.ansiBrightWhite": "#eceff4",
  },
}

/**
 * One Dark Pro theme colors
 * Atom's iconic dark theme
 */
const ONE_DARK: VSCodeFullTheme = {
  id: "one-dark",
  name: "One Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#282c34",
    "editor.foreground": "#abb2bf",
    "foreground": "#abb2bf",
    "sideBar.background": "#21252b",
    "sideBar.foreground": "#abb2bf",
    "sideBar.border": "#181a1f",
    "activityBar.background": "#21252b",
    "activityBar.foreground": "#abb2bf",
    "panel.background": "#21252b",
    "panel.border": "#181a1f",
    "tab.activeBackground": "#282c34",
    "tab.inactiveBackground": "#21252b",
    "tab.inactiveForeground": "#5c6370",
    "editorGroupHeader.tabsBackground": "#21252b",
    "dropdown.background": "#21252b",
    "dropdown.foreground": "#abb2bf",
    "input.background": "#1d1f23",
    "input.border": "#181a1f",
    "input.foreground": "#abb2bf",
    "focusBorder": "#528bff",
    "textLink.foreground": "#61afef",
    "textLink.activeForeground": "#528bff",
    "list.activeSelectionBackground": "#2c313a",
    "list.hoverBackground": "#2c313a80",
    "editor.selectionBackground": "#3e4451",
    "editorLineNumber.foreground": "#4b5263",
    "descriptionForeground": "#5c6370",
    "errorForeground": "#e06c75",
    "button.background": "#528bff",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#3e4451",
    "button.secondaryForeground": "#abb2bf",
    "terminal.background": "#282c34",
    "terminal.foreground": "#abb2bf",
    "terminal.ansiBlack": "#3f4451",
    "terminal.ansiRed": "#e06c75",
    "terminal.ansiGreen": "#98c379",
    "terminal.ansiYellow": "#e5c07b",
    "terminal.ansiBlue": "#61afef",
    "terminal.ansiMagenta": "#c678dd",
    "terminal.ansiCyan": "#56b6c2",
    "terminal.ansiWhite": "#abb2bf",
    "terminal.ansiBrightBlack": "#5c6370",
    "terminal.ansiBrightRed": "#e06c75",
    "terminal.ansiBrightGreen": "#98c379",
    "terminal.ansiBrightYellow": "#e5c07b",
    "terminal.ansiBrightBlue": "#61afef",
    "terminal.ansiBrightMagenta": "#c678dd",
    "terminal.ansiBrightCyan": "#56b6c2",
    "terminal.ansiBrightWhite": "#ffffff",
  },
}

/**
 * Monokai Pro theme colors
 * Classic Monokai with a modern touch
 */
const MONOKAI: VSCodeFullTheme = {
  id: "monokai",
  name: "Monokai",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#272822",
    "editor.foreground": "#f8f8f2",
    "foreground": "#f8f8f2",
    "sideBar.background": "#1e1f1c",
    "sideBar.foreground": "#f8f8f2",
    "sideBar.border": "#3b3a32",
    "activityBar.background": "#1e1f1c",
    "activityBar.foreground": "#f8f8f2",
    "panel.background": "#272822",
    "panel.border": "#3b3a32",
    "tab.activeBackground": "#272822",
    "tab.inactiveBackground": "#1e1f1c",
    "tab.inactiveForeground": "#75715e",
    "editorGroupHeader.tabsBackground": "#1e1f1c",
    "dropdown.background": "#1e1f1c",
    "dropdown.foreground": "#f8f8f2",
    "input.background": "#1e1f1c",
    "input.border": "#3b3a32",
    "input.foreground": "#f8f8f2",
    "focusBorder": "#a6e22e",
    "textLink.foreground": "#66d9ef",
    "textLink.activeForeground": "#a6e22e",
    "list.activeSelectionBackground": "#3b3a32",
    "list.hoverBackground": "#3b3a3280",
    "editor.selectionBackground": "#49483e",
    "editorLineNumber.foreground": "#75715e",
    "descriptionForeground": "#75715e",
    "errorForeground": "#f92672",
    "button.background": "#a6e22e",
    "button.foreground": "#272822",
    "button.secondaryBackground": "#3b3a32",
    "button.secondaryForeground": "#f8f8f2",
    "terminal.background": "#272822",
    "terminal.foreground": "#f8f8f2",
    "terminal.ansiBlack": "#272822",
    "terminal.ansiRed": "#f92672",
    "terminal.ansiGreen": "#a6e22e",
    "terminal.ansiYellow": "#f4bf75",
    "terminal.ansiBlue": "#66d9ef",
    "terminal.ansiMagenta": "#ae81ff",
    "terminal.ansiCyan": "#a1efe4",
    "terminal.ansiWhite": "#f8f8f2",
    "terminal.ansiBrightBlack": "#75715e",
    "terminal.ansiBrightRed": "#f92672",
    "terminal.ansiBrightGreen": "#a6e22e",
    "terminal.ansiBrightYellow": "#f4bf75",
    "terminal.ansiBrightBlue": "#66d9ef",
    "terminal.ansiBrightMagenta": "#ae81ff",
    "terminal.ansiBrightCyan": "#a1efe4",
    "terminal.ansiBrightWhite": "#f9f8f5",
  },
}

/**
 * Catppuccin Mocha theme colors
 * Soothing pastel theme for dark mode
 */
const CATPPUCCIN_MOCHA: VSCodeFullTheme = {
  id: "catppuccin-mocha",
  name: "Catppuccin Mocha",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "foreground": "#cdd6f4",
    "sideBar.background": "#181825",
    "sideBar.foreground": "#cdd6f4",
    "sideBar.border": "#313244",
    "activityBar.background": "#181825",
    "activityBar.foreground": "#cdd6f4",
    "panel.background": "#1e1e2e",
    "panel.border": "#313244",
    "tab.activeBackground": "#1e1e2e",
    "tab.inactiveBackground": "#181825",
    "tab.inactiveForeground": "#6c7086",
    "editorGroupHeader.tabsBackground": "#181825",
    "dropdown.background": "#313244",
    "dropdown.foreground": "#cdd6f4",
    "input.background": "#313244",
    "input.border": "#45475a",
    "input.foreground": "#cdd6f4",
    "focusBorder": "#cba6f7",
    "textLink.foreground": "#89b4fa",
    "textLink.activeForeground": "#cba6f7",
    "list.activeSelectionBackground": "#313244",
    "list.hoverBackground": "#45475a",
    "editor.selectionBackground": "#45475a",
    "editorLineNumber.foreground": "#6c7086",
    "descriptionForeground": "#a6adc8",
    "errorForeground": "#f38ba8",
    "button.background": "#cba6f7",
    "button.foreground": "#1e1e2e",
    "button.secondaryBackground": "#45475a",
    "button.secondaryForeground": "#cdd6f4",
    "terminal.background": "#1e1e2e",
    "terminal.foreground": "#cdd6f4",
    "terminal.ansiBlack": "#45475a",
    "terminal.ansiRed": "#f38ba8",
    "terminal.ansiGreen": "#a6e3a1",
    "terminal.ansiYellow": "#f9e2af",
    "terminal.ansiBlue": "#89b4fa",
    "terminal.ansiMagenta": "#cba6f7",
    "terminal.ansiCyan": "#94e2d5",
    "terminal.ansiWhite": "#bac2de",
    "terminal.ansiBrightBlack": "#585b70",
    "terminal.ansiBrightRed": "#f38ba8",
    "terminal.ansiBrightGreen": "#a6e3a1",
    "terminal.ansiBrightYellow": "#f9e2af",
    "terminal.ansiBrightBlue": "#89b4fa",
    "terminal.ansiBrightMagenta": "#cba6f7",
    "terminal.ansiBrightCyan": "#94e2d5",
    "terminal.ansiBrightWhite": "#a6adc8",
  },
}

/**
 * Catppuccin Latte theme colors
 * Soothing pastel theme for light mode
 */
const CATPPUCCIN_LATTE: VSCodeFullTheme = {
  id: "catppuccin-latte",
  name: "Catppuccin Latte",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#eff1f5",
    "editor.foreground": "#4c4f69",
    "foreground": "#4c4f69",
    "sideBar.background": "#e6e9ef",
    "sideBar.foreground": "#4c4f69",
    "sideBar.border": "#ccd0da",
    "activityBar.background": "#e6e9ef",
    "activityBar.foreground": "#4c4f69",
    "panel.background": "#eff1f5",
    "panel.border": "#ccd0da",
    "tab.activeBackground": "#eff1f5",
    "tab.inactiveBackground": "#e6e9ef",
    "tab.inactiveForeground": "#9ca0b0",
    "editorGroupHeader.tabsBackground": "#e6e9ef",
    "dropdown.background": "#eff1f5",
    "dropdown.foreground": "#4c4f69",
    "input.background": "#e6e9ef",
    "input.border": "#ccd0da",
    "input.foreground": "#4c4f69",
    "focusBorder": "#8839ef",
    "textLink.foreground": "#1e66f5",
    "textLink.activeForeground": "#8839ef",
    "list.activeSelectionBackground": "#ccd0da",
    "list.hoverBackground": "#dce0e8",
    "editor.selectionBackground": "#acb0be",
    "editorLineNumber.foreground": "#9ca0b0",
    "descriptionForeground": "#6c6f85",
    "errorForeground": "#d20f39",
    "button.background": "#8839ef",
    "button.foreground": "#eff1f5",
    "button.secondaryBackground": "#ccd0da",
    "button.secondaryForeground": "#4c4f69",
    "terminal.background": "#eff1f5",
    "terminal.foreground": "#4c4f69",
    "terminal.ansiBlack": "#5c5f77",
    "terminal.ansiRed": "#d20f39",
    "terminal.ansiGreen": "#40a02b",
    "terminal.ansiYellow": "#df8e1d",
    "terminal.ansiBlue": "#1e66f5",
    "terminal.ansiMagenta": "#8839ef",
    "terminal.ansiCyan": "#179299",
    "terminal.ansiWhite": "#acb0be",
    "terminal.ansiBrightBlack": "#6c6f85",
    "terminal.ansiBrightRed": "#d20f39",
    "terminal.ansiBrightGreen": "#40a02b",
    "terminal.ansiBrightYellow": "#df8e1d",
    "terminal.ansiBrightBlue": "#1e66f5",
    "terminal.ansiBrightMagenta": "#8839ef",
    "terminal.ansiBrightCyan": "#179299",
    "terminal.ansiBrightWhite": "#4c4f69",
  },
}

/**
 * Gruvbox Dark theme colors
 * Retro groove color scheme
 */
const GRUVBOX_DARK: VSCodeFullTheme = {
  id: "gruvbox-dark",
  name: "Gruvbox Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#282828",
    "editor.foreground": "#ebdbb2",
    "foreground": "#ebdbb2",
    "sideBar.background": "#1d2021",
    "sideBar.foreground": "#ebdbb2",
    "sideBar.border": "#3c3836",
    "activityBar.background": "#1d2021",
    "activityBar.foreground": "#ebdbb2",
    "panel.background": "#282828",
    "panel.border": "#3c3836",
    "tab.activeBackground": "#282828",
    "tab.inactiveBackground": "#1d2021",
    "tab.inactiveForeground": "#928374",
    "editorGroupHeader.tabsBackground": "#1d2021",
    "dropdown.background": "#3c3836",
    "dropdown.foreground": "#ebdbb2",
    "input.background": "#3c3836",
    "input.border": "#504945",
    "input.foreground": "#ebdbb2",
    "focusBorder": "#fe8019",
    "textLink.foreground": "#83a598",
    "textLink.activeForeground": "#fe8019",
    "list.activeSelectionBackground": "#504945",
    "list.hoverBackground": "#3c3836",
    "editor.selectionBackground": "#504945",
    "editorLineNumber.foreground": "#665c54",
    "descriptionForeground": "#a89984",
    "errorForeground": "#fb4934",
    "button.background": "#fe8019",
    "button.foreground": "#282828",
    "button.secondaryBackground": "#504945",
    "button.secondaryForeground": "#ebdbb2",
    "terminal.background": "#282828",
    "terminal.foreground": "#ebdbb2",
    "terminal.ansiBlack": "#282828",
    "terminal.ansiRed": "#cc241d",
    "terminal.ansiGreen": "#98971a",
    "terminal.ansiYellow": "#d79921",
    "terminal.ansiBlue": "#458588",
    "terminal.ansiMagenta": "#b16286",
    "terminal.ansiCyan": "#689d6a",
    "terminal.ansiWhite": "#a89984",
    "terminal.ansiBrightBlack": "#928374",
    "terminal.ansiBrightRed": "#fb4934",
    "terminal.ansiBrightGreen": "#b8bb26",
    "terminal.ansiBrightYellow": "#fabd2f",
    "terminal.ansiBrightBlue": "#83a598",
    "terminal.ansiBrightMagenta": "#d3869b",
    "terminal.ansiBrightCyan": "#8ec07c",
    "terminal.ansiBrightWhite": "#ebdbb2",
  },
}

/**
 * Gruvbox Light theme colors
 * Retro groove color scheme (light variant)
 */
const GRUVBOX_LIGHT: VSCodeFullTheme = {
  id: "gruvbox-light",
  name: "Gruvbox Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#fbf1c7",
    "editor.foreground": "#3c3836",
    "foreground": "#3c3836",
    "sideBar.background": "#f2e5bc",
    "sideBar.foreground": "#3c3836",
    "sideBar.border": "#ebdbb2",
    "activityBar.background": "#f2e5bc",
    "activityBar.foreground": "#3c3836",
    "panel.background": "#fbf1c7",
    "panel.border": "#ebdbb2",
    "tab.activeBackground": "#fbf1c7",
    "tab.inactiveBackground": "#f2e5bc",
    "tab.inactiveForeground": "#928374",
    "editorGroupHeader.tabsBackground": "#f2e5bc",
    "dropdown.background": "#fbf1c7",
    "dropdown.foreground": "#3c3836",
    "input.background": "#f2e5bc",
    "input.border": "#d5c4a1",
    "input.foreground": "#3c3836",
    "focusBorder": "#d65d0e",
    "textLink.foreground": "#076678",
    "textLink.activeForeground": "#d65d0e",
    "list.activeSelectionBackground": "#ebdbb2",
    "list.hoverBackground": "#f2e5bc",
    "editor.selectionBackground": "#d5c4a1",
    "editorLineNumber.foreground": "#928374",
    "descriptionForeground": "#7c6f64",
    "errorForeground": "#cc241d",
    "button.background": "#d65d0e",
    "button.foreground": "#fbf1c7",
    "button.secondaryBackground": "#ebdbb2",
    "button.secondaryForeground": "#3c3836",
    "terminal.background": "#fbf1c7",
    "terminal.foreground": "#3c3836",
    "terminal.ansiBlack": "#3c3836",
    "terminal.ansiRed": "#cc241d",
    "terminal.ansiGreen": "#98971a",
    "terminal.ansiYellow": "#d79921",
    "terminal.ansiBlue": "#458588",
    "terminal.ansiMagenta": "#b16286",
    "terminal.ansiCyan": "#689d6a",
    "terminal.ansiWhite": "#7c6f64",
    "terminal.ansiBrightBlack": "#928374",
    "terminal.ansiBrightRed": "#9d0006",
    "terminal.ansiBrightGreen": "#79740e",
    "terminal.ansiBrightYellow": "#b57614",
    "terminal.ansiBrightBlue": "#076678",
    "terminal.ansiBrightMagenta": "#8f3f71",
    "terminal.ansiBrightCyan": "#427b58",
    "terminal.ansiBrightWhite": "#3c3836",
  },
}

/**
 * Tokyo Night theme colors
 * Clean visual Studio Code theme with Tokyo city-inspired colors
 */
const TOKYO_NIGHT: VSCodeFullTheme = {
  id: "tokyo-night",
  name: "Tokyo Night",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#1a1b26",
    "editor.foreground": "#a9b1d6",
    "foreground": "#a9b1d6",
    "sideBar.background": "#1a1b26",
    "sideBar.foreground": "#a9b1d6",
    "sideBar.border": "#101014",
    "activityBar.background": "#1a1b26",
    "activityBar.foreground": "#a9b1d6",
    "panel.background": "#1a1b26",
    "panel.border": "#101014",
    "tab.activeBackground": "#1a1b26",
    "tab.inactiveBackground": "#16161e",
    "tab.inactiveForeground": "#565f89",
    "editorGroupHeader.tabsBackground": "#16161e",
    "dropdown.background": "#1a1b26",
    "dropdown.foreground": "#a9b1d6",
    "input.background": "#1a1b26",
    "input.border": "#3b4261",
    "input.foreground": "#a9b1d6",
    "focusBorder": "#7aa2f7",
    "textLink.foreground": "#7aa2f7",
    "textLink.activeForeground": "#bb9af7",
    "list.activeSelectionBackground": "#2f3549",
    "list.hoverBackground": "#292e42",
    "editor.selectionBackground": "#364a82",
    "editorLineNumber.foreground": "#3b4261",
    "descriptionForeground": "#565f89",
    "errorForeground": "#f7768e",
    "button.background": "#7aa2f7",
    "button.foreground": "#1a1b26",
    "button.secondaryBackground": "#3b4261",
    "button.secondaryForeground": "#a9b1d6",
    "terminal.background": "#1a1b26",
    "terminal.foreground": "#a9b1d6",
    "terminal.ansiBlack": "#414868",
    "terminal.ansiRed": "#f7768e",
    "terminal.ansiGreen": "#9ece6a",
    "terminal.ansiYellow": "#e0af68",
    "terminal.ansiBlue": "#7aa2f7",
    "terminal.ansiMagenta": "#bb9af7",
    "terminal.ansiCyan": "#7dcfff",
    "terminal.ansiWhite": "#c0caf5",
    "terminal.ansiBrightBlack": "#565f89",
    "terminal.ansiBrightRed": "#f7768e",
    "terminal.ansiBrightGreen": "#9ece6a",
    "terminal.ansiBrightYellow": "#e0af68",
    "terminal.ansiBrightBlue": "#7aa2f7",
    "terminal.ansiBrightMagenta": "#bb9af7",
    "terminal.ansiBrightCyan": "#7dcfff",
    "terminal.ansiBrightWhite": "#c0caf5",
  },
}

/**
 * Solarized Dark theme colors
 * Precision colors for machines and people
 */
const SOLARIZED_DARK: VSCodeFullTheme = {
  id: "solarized-dark",
  name: "Solarized Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#002b36",
    "editor.foreground": "#839496",
    "foreground": "#839496",
    "sideBar.background": "#00212b",
    "sideBar.foreground": "#839496",
    "sideBar.border": "#073642",
    "activityBar.background": "#00212b",
    "activityBar.foreground": "#839496",
    "panel.background": "#002b36",
    "panel.border": "#073642",
    "tab.activeBackground": "#002b36",
    "tab.inactiveBackground": "#00212b",
    "tab.inactiveForeground": "#586e75",
    "editorGroupHeader.tabsBackground": "#00212b",
    "dropdown.background": "#073642",
    "dropdown.foreground": "#839496",
    "input.background": "#073642",
    "input.border": "#0a4858",
    "input.foreground": "#839496",
    "focusBorder": "#268bd2",
    "textLink.foreground": "#268bd2",
    "textLink.activeForeground": "#2aa198",
    "list.activeSelectionBackground": "#073642",
    "list.hoverBackground": "#073642cc",
    "editor.selectionBackground": "#073642",
    "editorLineNumber.foreground": "#586e75",
    "descriptionForeground": "#657b83",
    "errorForeground": "#dc322f",
    "button.background": "#268bd2",
    "button.foreground": "#fdf6e3",
    "button.secondaryBackground": "#073642",
    "button.secondaryForeground": "#839496",
    "terminal.background": "#002b36",
    "terminal.foreground": "#839496",
    "terminal.ansiBlack": "#073642",
    "terminal.ansiRed": "#dc322f",
    "terminal.ansiGreen": "#859900",
    "terminal.ansiYellow": "#b58900",
    "terminal.ansiBlue": "#268bd2",
    "terminal.ansiMagenta": "#d33682",
    "terminal.ansiCyan": "#2aa198",
    "terminal.ansiWhite": "#eee8d5",
    "terminal.ansiBrightBlack": "#586e75",
    "terminal.ansiBrightRed": "#cb4b16",
    "terminal.ansiBrightGreen": "#859900",
    "terminal.ansiBrightYellow": "#b58900",
    "terminal.ansiBrightBlue": "#268bd2",
    "terminal.ansiBrightMagenta": "#6c71c4",
    "terminal.ansiBrightCyan": "#2aa198",
    "terminal.ansiBrightWhite": "#fdf6e3",
  },
}

/**
 * Solarized Light theme colors
 * Precision colors for machines and people (light variant)
 */
const SOLARIZED_LIGHT: VSCodeFullTheme = {
  id: "solarized-light",
  name: "Solarized Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#fdf6e3",
    "editor.foreground": "#657b83",
    "foreground": "#657b83",
    "sideBar.background": "#eee8d5",
    "sideBar.foreground": "#657b83",
    "sideBar.border": "#dcd5c0",
    "activityBar.background": "#eee8d5",
    "activityBar.foreground": "#657b83",
    "panel.background": "#fdf6e3",
    "panel.border": "#dcd5c0",
    "tab.activeBackground": "#fdf6e3",
    "tab.inactiveBackground": "#eee8d5",
    "tab.inactiveForeground": "#93a1a1",
    "editorGroupHeader.tabsBackground": "#eee8d5",
    "dropdown.background": "#fdf6e3",
    "dropdown.foreground": "#657b83",
    "input.background": "#eee8d5",
    "input.border": "#dcd5c0",
    "input.foreground": "#657b83",
    "focusBorder": "#268bd2",
    "textLink.foreground": "#268bd2",
    "textLink.activeForeground": "#2aa198",
    "list.activeSelectionBackground": "#eee8d5",
    "list.hoverBackground": "#eee8d5cc",
    "editor.selectionBackground": "#eee8d5",
    "editorLineNumber.foreground": "#93a1a1",
    "descriptionForeground": "#839496",
    "errorForeground": "#dc322f",
    "button.background": "#268bd2",
    "button.foreground": "#fdf6e3",
    "button.secondaryBackground": "#eee8d5",
    "button.secondaryForeground": "#657b83",
    "terminal.background": "#fdf6e3",
    "terminal.foreground": "#657b83",
    "terminal.ansiBlack": "#073642",
    "terminal.ansiRed": "#dc322f",
    "terminal.ansiGreen": "#859900",
    "terminal.ansiYellow": "#b58900",
    "terminal.ansiBlue": "#268bd2",
    "terminal.ansiMagenta": "#d33682",
    "terminal.ansiCyan": "#2aa198",
    "terminal.ansiWhite": "#eee8d5",
    "terminal.ansiBrightBlack": "#586e75",
    "terminal.ansiBrightRed": "#cb4b16",
    "terminal.ansiBrightGreen": "#859900",
    "terminal.ansiBrightYellow": "#b58900",
    "terminal.ansiBrightBlue": "#268bd2",
    "terminal.ansiBrightMagenta": "#6c71c4",
    "terminal.ansiBrightCyan": "#2aa198",
    "terminal.ansiBrightWhite": "#fdf6e3",
  },
}

/**
 * Synthwave '84 theme colors
 * Retro futuristic neon theme
 */
const SYNTHWAVE_84: VSCodeFullTheme = {
  id: "synthwave-84",
  name: "Synthwave '84",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#262335",
    "editor.foreground": "#f0eff1",
    "foreground": "#f0eff1",
    "sideBar.background": "#241b2f",
    "sideBar.foreground": "#f0eff1",
    "sideBar.border": "#34294f",
    "activityBar.background": "#1a1726",
    "activityBar.foreground": "#f0eff1",
    "panel.background": "#262335",
    "panel.border": "#34294f",
    "tab.activeBackground": "#262335",
    "tab.inactiveBackground": "#1a1726",
    "tab.inactiveForeground": "#8f7eb8",
    "editorGroupHeader.tabsBackground": "#1a1726",
    "dropdown.background": "#34294f",
    "dropdown.foreground": "#f0eff1",
    "input.background": "#241b2f",
    "input.border": "#34294f",
    "input.foreground": "#f0eff1",
    "focusBorder": "#ff7edb",
    "textLink.foreground": "#36f9f6",
    "textLink.activeForeground": "#ff7edb",
    "list.activeSelectionBackground": "#463465",
    "list.hoverBackground": "#34294f",
    "editor.selectionBackground": "#463465",
    "editorLineNumber.foreground": "#8f7eb8",
    "descriptionForeground": "#8f7eb8",
    "errorForeground": "#fe4450",
    "button.background": "#ff7edb",
    "button.foreground": "#262335",
    "button.secondaryBackground": "#34294f",
    "button.secondaryForeground": "#f0eff1",
    "terminal.background": "#262335",
    "terminal.foreground": "#f0eff1",
    "terminal.ansiBlack": "#262335",
    "terminal.ansiRed": "#fe4450",
    "terminal.ansiGreen": "#72f1b8",
    "terminal.ansiYellow": "#fede5d",
    "terminal.ansiBlue": "#36f9f6",
    "terminal.ansiMagenta": "#ff7edb",
    "terminal.ansiCyan": "#36f9f6",
    "terminal.ansiWhite": "#f0eff1",
    "terminal.ansiBrightBlack": "#8f7eb8",
    "terminal.ansiBrightRed": "#fe4450",
    "terminal.ansiBrightGreen": "#72f1b8",
    "terminal.ansiBrightYellow": "#fede5d",
    "terminal.ansiBrightBlue": "#36f9f6",
    "terminal.ansiBrightMagenta": "#ff7edb",
    "terminal.ansiBrightCyan": "#36f9f6",
    "terminal.ansiBrightWhite": "#ffffff",
  },
}

/**
 * GitHub Dark theme colors
 * GitHub's dark mode theme
 */
const GITHUB_DARK: VSCodeFullTheme = {
  id: "github-dark",
  name: "GitHub Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "foreground": "#c9d1d9",
    "sideBar.background": "#010409",
    "sideBar.foreground": "#c9d1d9",
    "sideBar.border": "#30363d",
    "activityBar.background": "#0d1117",
    "activityBar.foreground": "#c9d1d9",
    "panel.background": "#0d1117",
    "panel.border": "#30363d",
    "tab.activeBackground": "#0d1117",
    "tab.inactiveBackground": "#010409",
    "tab.inactiveForeground": "#8b949e",
    "editorGroupHeader.tabsBackground": "#010409",
    "dropdown.background": "#161b22",
    "dropdown.foreground": "#c9d1d9",
    "input.background": "#0d1117",
    "input.border": "#30363d",
    "input.foreground": "#c9d1d9",
    "focusBorder": "#58a6ff",
    "textLink.foreground": "#58a6ff",
    "textLink.activeForeground": "#79c0ff",
    "list.activeSelectionBackground": "#21262d",
    "list.hoverBackground": "#161b22",
    "editor.selectionBackground": "#264f78",
    "editorLineNumber.foreground": "#6e7681",
    "descriptionForeground": "#8b949e",
    "errorForeground": "#f85149",
    "button.background": "#238636",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#21262d",
    "button.secondaryForeground": "#c9d1d9",
    "terminal.background": "#0d1117",
    "terminal.foreground": "#c9d1d9",
    "terminal.ansiBlack": "#484f58",
    "terminal.ansiRed": "#ff7b72",
    "terminal.ansiGreen": "#3fb950",
    "terminal.ansiYellow": "#d29922",
    "terminal.ansiBlue": "#58a6ff",
    "terminal.ansiMagenta": "#bc8cff",
    "terminal.ansiCyan": "#39c5cf",
    "terminal.ansiWhite": "#b1bac4",
    "terminal.ansiBrightBlack": "#6e7681",
    "terminal.ansiBrightRed": "#ffa198",
    "terminal.ansiBrightGreen": "#56d364",
    "terminal.ansiBrightYellow": "#e3b341",
    "terminal.ansiBrightBlue": "#79c0ff",
    "terminal.ansiBrightMagenta": "#d2a8ff",
    "terminal.ansiBrightCyan": "#56d4dd",
    "terminal.ansiBrightWhite": "#f0f6fc",
  },
}

/**
 * GitHub Light theme colors
 * GitHub's light mode theme
 */
const GITHUB_LIGHT: VSCodeFullTheme = {
  id: "github-light",
  name: "GitHub Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#24292f",
    "foreground": "#24292f",
    "sideBar.background": "#f6f8fa",
    "sideBar.foreground": "#24292f",
    "sideBar.border": "#d0d7de",
    "activityBar.background": "#ffffff",
    "activityBar.foreground": "#24292f",
    "panel.background": "#ffffff",
    "panel.border": "#d0d7de",
    "tab.activeBackground": "#ffffff",
    "tab.inactiveBackground": "#f6f8fa",
    "tab.inactiveForeground": "#57606a",
    "editorGroupHeader.tabsBackground": "#f6f8fa",
    "dropdown.background": "#ffffff",
    "dropdown.foreground": "#24292f",
    "input.background": "#ffffff",
    "input.border": "#d0d7de",
    "input.foreground": "#24292f",
    "focusBorder": "#0969da",
    "textLink.foreground": "#0969da",
    "textLink.activeForeground": "#0550ae",
    "list.activeSelectionBackground": "#afb8c133",
    "list.hoverBackground": "#f6f8fa",
    "editor.selectionBackground": "#add6ff",
    "editorLineNumber.foreground": "#8c959f",
    "descriptionForeground": "#57606a",
    "errorForeground": "#cf222e",
    "button.background": "#1f883d",
    "button.foreground": "#ffffff",
    "button.secondaryBackground": "#e7ecf0",
    "button.secondaryForeground": "#24292f",
    "terminal.background": "#ffffff",
    "terminal.foreground": "#24292f",
    "terminal.ansiBlack": "#24292f",
    "terminal.ansiRed": "#cf222e",
    "terminal.ansiGreen": "#116329",
    "terminal.ansiYellow": "#4d2d00",
    "terminal.ansiBlue": "#0969da",
    "terminal.ansiMagenta": "#8250df",
    "terminal.ansiCyan": "#1b7c83",
    "terminal.ansiWhite": "#6e7781",
    "terminal.ansiBrightBlack": "#57606a",
    "terminal.ansiBrightRed": "#a40e26",
    "terminal.ansiBrightGreen": "#1a7f37",
    "terminal.ansiBrightYellow": "#633c01",
    "terminal.ansiBrightBlue": "#218bff",
    "terminal.ansiBrightMagenta": "#a475f9",
    "terminal.ansiBrightCyan": "#3192aa",
    "terminal.ansiBrightWhite": "#8c959f",
  },
}

/**
 * Ayu Dark theme colors
 * Modern dark theme with warm colors
 */
const AYU_DARK: VSCodeFullTheme = {
  id: "ayu-dark",
  name: "Ayu Dark",
  type: "dark",
  source: "builtin",
  colors: {
    "editor.background": "#0d1017",
    "editor.foreground": "#bfbdb6",
    "foreground": "#bfbdb6",
    "sideBar.background": "#0b0e14",
    "sideBar.foreground": "#bfbdb6",
    "sideBar.border": "#11151c",
    "activityBar.background": "#0b0e14",
    "activityBar.foreground": "#bfbdb6",
    "panel.background": "#0d1017",
    "panel.border": "#11151c",
    "tab.activeBackground": "#0d1017",
    "tab.inactiveBackground": "#0b0e14",
    "tab.inactiveForeground": "#565b66",
    "editorGroupHeader.tabsBackground": "#0b0e14",
    "dropdown.background": "#11151c",
    "dropdown.foreground": "#bfbdb6",
    "input.background": "#0b0e14",
    "input.border": "#11151c",
    "input.foreground": "#bfbdb6",
    "focusBorder": "#e6b450",
    "textLink.foreground": "#e6b450",
    "textLink.activeForeground": "#ffb454",
    "list.activeSelectionBackground": "#1a1f29",
    "list.hoverBackground": "#11151c",
    "editor.selectionBackground": "#409fff3d",
    "editorLineNumber.foreground": "#3d424d",
    "descriptionForeground": "#565b66",
    "errorForeground": "#d95757",
    "button.background": "#e6b450",
    "button.foreground": "#0d1017",
    "button.secondaryBackground": "#1a1f29",
    "button.secondaryForeground": "#bfbdb6",
    "terminal.background": "#0d1017",
    "terminal.foreground": "#bfbdb6",
    "terminal.ansiBlack": "#11151c",
    "terminal.ansiRed": "#f26d78",
    "terminal.ansiGreen": "#aad94c",
    "terminal.ansiYellow": "#e6b450",
    "terminal.ansiBlue": "#59c2ff",
    "terminal.ansiMagenta": "#d2a6ff",
    "terminal.ansiCyan": "#95e6cb",
    "terminal.ansiWhite": "#bfbdb6",
    "terminal.ansiBrightBlack": "#565b66",
    "terminal.ansiBrightRed": "#f26d78",
    "terminal.ansiBrightGreen": "#aad94c",
    "terminal.ansiBrightYellow": "#e6b450",
    "terminal.ansiBrightBlue": "#59c2ff",
    "terminal.ansiBrightMagenta": "#d2a6ff",
    "terminal.ansiBrightCyan": "#95e6cb",
    "terminal.ansiBrightWhite": "#e6e1cf",
  },
}

/**
 * Ayu Light theme colors
 * Modern light theme with warm colors
 */
const AYU_LIGHT: VSCodeFullTheme = {
  id: "ayu-light",
  name: "Ayu Light",
  type: "light",
  source: "builtin",
  colors: {
    "editor.background": "#fcfcfc",
    "editor.foreground": "#5c6166",
    "foreground": "#5c6166",
    "sideBar.background": "#f8f9fa",
    "sideBar.foreground": "#5c6166",
    "sideBar.border": "#f0f0f0",
    "activityBar.background": "#f8f9fa",
    "activityBar.foreground": "#5c6166",
    "panel.background": "#fcfcfc",
    "panel.border": "#f0f0f0",
    "tab.activeBackground": "#fcfcfc",
    "tab.inactiveBackground": "#f8f9fa",
    "tab.inactiveForeground": "#8a9199",
    "editorGroupHeader.tabsBackground": "#f8f9fa",
    "dropdown.background": "#fcfcfc",
    "dropdown.foreground": "#5c6166",
    "input.background": "#f8f9fa",
    "input.border": "#f0f0f0",
    "input.foreground": "#5c6166",
    "focusBorder": "#f2ae49",
    "textLink.foreground": "#f2ae49",
    "textLink.activeForeground": "#fa8d3e",
    "list.activeSelectionBackground": "#e8e8e8",
    "list.hoverBackground": "#f0f0f0",
    "editor.selectionBackground": "#035bd626",
    "editorLineNumber.foreground": "#acb6bf",
    "descriptionForeground": "#8a9199",
    "errorForeground": "#e65050",
    "button.background": "#f2ae49",
    "button.foreground": "#fcfcfc",
    "button.secondaryBackground": "#e8e8e8",
    "button.secondaryForeground": "#5c6166",
    "terminal.background": "#fcfcfc",
    "terminal.foreground": "#5c6166",
    "terminal.ansiBlack": "#1a1f29",
    "terminal.ansiRed": "#f07171",
    "terminal.ansiGreen": "#86b300",
    "terminal.ansiYellow": "#f2ae49",
    "terminal.ansiBlue": "#399ee6",
    "terminal.ansiMagenta": "#a37acc",
    "terminal.ansiCyan": "#4cbf99",
    "terminal.ansiWhite": "#5c6166",
    "terminal.ansiBrightBlack": "#8a9199",
    "terminal.ansiBrightRed": "#f07171",
    "terminal.ansiBrightGreen": "#86b300",
    "terminal.ansiBrightYellow": "#f2ae49",
    "terminal.ansiBrightBlue": "#399ee6",
    "terminal.ansiBrightMagenta": "#a37acc",
    "terminal.ansiBrightCyan": "#4cbf99",
    "terminal.ansiBrightWhite": "#1a1f29",
  },
}

/**
 * All built-in themes
 */
export const BUILTIN_THEMES: VSCodeFullTheme[] = [
  // 21st Default themes (first)
  TWENTYFIRST_DARK,
  TWENTYFIRST_LIGHT,
  // Cursor themes
  CURSOR_DARK,
  CURSOR_LIGHT,
  CURSOR_MIDNIGHT,
  // Dark themes
  CLAUDE_DARK,
  VESPER_DARK,
  VITESSE_DARK,
  MIN_DARK,
  DRACULA,
  NORD,
  ONE_DARK,
  MONOKAI,
  CATPPUCCIN_MOCHA,
  GRUVBOX_DARK,
  TOKYO_NIGHT,
  SOLARIZED_DARK,
  SYNTHWAVE_84,
  GITHUB_DARK,
  AYU_DARK,
  // Light themes
  CLAUDE_LIGHT,
  VITESSE_LIGHT,
  MIN_LIGHT,
  CATPPUCCIN_LATTE,
  GRUVBOX_LIGHT,
  SOLARIZED_LIGHT,
  GITHUB_LIGHT,
  AYU_LIGHT,
]

/**
 * Get theme by ID
 */
export function getBuiltinThemeById(id: string): VSCodeFullTheme | undefined {
  return BUILTIN_THEMES.find((theme) => theme.id === id)
}

/**
 * Get themes by type
 */
export function getBuiltinThemesByType(type: "light" | "dark"): VSCodeFullTheme[] {
  return BUILTIN_THEMES.filter((theme) => theme.type === type)
}

/**
 * Default theme IDs for light/dark modes
 */
export const DEFAULT_LIGHT_THEME_ID = "21st-light"
export const DEFAULT_DARK_THEME_ID = "21st-dark"
